[2024-04-04T22:42:31.476+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_csv_to_iceberg2.consume_events manual__2024-04-04T22:42:18.139012+00:00 [queued]>
[2024-04-04T22:42:31.485+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_csv_to_iceberg2.consume_events manual__2024-04-04T22:42:18.139012+00:00 [queued]>
[2024-04-04T22:42:31.485+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 1000000000
[2024-04-04T22:42:31.498+0000] {taskinstance.py:2191} INFO - Executing <Task(RabbitMQPythonOperator): consume_events> on 2024-04-04 22:42:18.139012+00:00
[2024-04-04T22:42:31.502+0000] {standard_task_runner.py:60} INFO - Started process 80 to run task
[2024-04-04T22:42:31.504+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ingest_csv_to_iceberg2', 'consume_events', 'manual__2024-04-04T22:42:18.139012+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/ingest_csv_to_iceberg2.py', '--cfg-path', '/tmp/tmpq9k0oab5']
[2024-04-04T22:42:31.505+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask consume_events
[2024-04-04T22:42:31.517+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-04-04T22:42:31.549+0000] {task_command.py:423} INFO - Running <TaskInstance: ingest_csv_to_iceberg2.consume_events manual__2024-04-04T22:42:18.139012+00:00 [running]> on host 57040b15b2ad
[2024-04-04T22:42:31.602+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_csv_to_iceberg2' AIRFLOW_CTX_TASK_ID='consume_events' AIRFLOW_CTX_EXECUTION_DATE='2024-04-04T22:42:18.139012+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-04T22:42:18.139012+00:00'
[2024-04-04T22:42:31.616+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/opt/airflow/dags/modules/providers/operators/rabbitmq.py", line 76, in execute
    message = self.hook.pull(self.queue_name)
  File "/home/airflow/.local/lib/python3.10/site-packages/rabbitmq_provider/hooks/rabbitmq.py", line 123, in pull
    connection = self.get_conn()
  File "/home/airflow/.local/lib/python3.10/site-packages/rabbitmq_provider/hooks/rabbitmq.py", line 48, in get_conn
    conn = self.get_connection(self.rabbitmq_conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `rabbitmq_conn` isn't defined
[2024-04-04T22:42:31.622+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_csv_to_iceberg2, task_id=consume_events, execution_date=20240404T224218, start_date=20240404T224231, end_date=20240404T224231
[2024-04-04T22:42:31.631+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task consume_events (The conn_id `rabbitmq_conn` isn't defined; 80)
[2024-04-04T22:42:31.677+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-04T22:42:31.699+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
